## 4.函数

Rust的函数使用关键字`fn`开头，可以有一系列的输入参数，还有**一个**返回类型。

Rust编写的可执行程序的入口就是fn main () 函数。函数的参数列表同let语句一样，也是一个“模式结构”：

```rust
fn add1(t: (i32, i32)) -> i32 {
    t.0 + t.1
}

fn add2((x, y): (i32, i32)) -> i32 {
    x + y
}
```

函数返回可以使用return语句，也可以使用表达式。

函数也可以不写返回类型，在这种情况下，编译器会认为返回类型是`unit ()`。 此处和表达式的规定是一致的 。

Rust中函数可以被复制到一个变量中，这个同Golang十分像：

```rust
let func = add1;
println!("{}", func((1, 2)));
```

每一个函数都具有自己单独的类型，但是这个类型可以自动转换到**fn类型** 。

```rust
fn add1(t: (i32, i32)) -> i32 {
    t.0 + t.1
}

fn add3(t: (i32, i32)) -> i32 {
    t.0 + t.1 + 1 + 2
}

fn main(){
  let mut func = add1;
  // 编译报错
	func=add3; 
}
```

编译报错提示"expected fn item, found a different fn item"。

在Rust中，每个函数都对应其**自己特有的类型**。即使参数列表和返回值都一样的两个函数，他们的类型也不相同，这个跟Golang完全相反。

修复方法：将func的类型设置为通用的**fn类型**。

```rust
// 解决方法一：
let mut func = add1 as fn((i32, i32)) -> i32;
func = add3;
println!("{}", func((1, 9)))

// 解决方法二：
let mut func: fn((i32, i32)) -> i32 = add1;
func = add3;
println!("{}", func((1, 9)))
```

以上两种写法都能修复编译的错误。 但是，我们不能在参数、 返回值类型不同的情况下作类型转换。

Rust的函数体内也允许定义其他item，包括静态变量、 常量、函数 、trait、类型、模块等 。

```rust
fn test_inner() {
    static INNER_STATIC: i64 = 1024;
    // 函数体内部定义函数
    fn internal_func(x: i64) -> i64 {
        x + 1
    }
		// 函数体内定义struct tuple
    struct InnerStruct(i64);
    impl InnerStruct {
        fn inner_func2(&mut self) {
            self.0 = internal_func(self.0);
        }
    }
    // 真正的函数体
    let mut t = InnerStruct(INNER_STATIC);
    t.inner_func2();
    println!("{}", t.0)
}

```



### 4.1 何时在函数内部定义新函数呢？

当你需要一些 item仅在此函数内有用的时候，可以把它们直接定义到函数体内，以避免 污染外部的命名空间 。

### 4.2 发散函数

Rust支持一种特殊的**发散函数**( Diverging functions)，它的返回类型是感叹号 `!`。如果一个函数无法正常返回，那么可以这样写：

```rust
fn diverges()->!{
    panic!("never return");
}
```

这是因为Rust中的panic！会直接导致**栈展开**，所以这个函数调用后面的代码都将无法执行。

发散类型的最大特点就是，它可以被转换为任意一个类型：

```rust
let a: &str = diverges();
let b: f64 = diverges();
```

那么为什么需要这样一种类型呢？看：

```rust
let x = true;
let p = if x { 100 } else { panic!("error") };
```

因为if ... else ... 每个分支的返回类型必须一致，所以`!`类型必须可以与任意类型相容。

#### 4.2.1 Rust中永远不会返回的情况

- panic!以及基于它实现的各种函数/宏，比如：unimplemented !、 unreachable! ;
- 死循环loop{}；
- 退出进程函数std::process::exit以及类似的libc中的exec一类函数

### 4.3 main函数

在大部分主流操作系统上，一个进程开始执行的时候可以接受一系列的**参数**，退出的时 候也可以返回一个**错误码** 。 许多编程语言也因此为 main 函数设计了参数和返回值类型 。 以C语言为例：

```c
int main(void);
int main();
int main(int argc,char **argv);
int main(int argc,char *argv[]);
int main(int argc,char **argv,char **env);
```

Rust则不同，传递参数和返回状态码都是由单独的API来完成：

```rust
fn main(){
      for arg in std::env::args() {
        println!("{}", arg);
    }
    std::process::exit(0);
}
```

编译后，命令行执行：

```shell
$ ./main -a --b -- c d-
```

输出结果：

```
./main
-a
--b
--
c
d-
```

进程可以在任何时候调用exit() 直接退出， 退出时候的错误码由exit()函数的参数指定。

#### 4.3.1 读取环境变量

```rust
fn main(){
      for arg in std::env::args() {
        match std::env::var(&arg) {
            Ok(val) => println!("{}: {:?}", &arg, val),
            Err(e) => println!("couldn't find environment {},{}", &arg, e)
        }
    }
    println!("All environment varible count {}", std::env::vars().count());
}
```

编译后，命令行执行：

```shell
$ ./main CONDA_PYTHON_EXE
```

输出：

```shell
couldn't find environment ./main,environment variable not found
CONDA_PYTHON_EXE: "/anaconda3/bin/python"
All environment varible count 40
```

这相当于输入了两个参数"./main"和"CONDA_PYTHON_EXE"，然后在当前终端的所有环境变量中查找这两个环境变量名，如果有就返回。

注：

var() 函数可以接受一个字符串类型参数，用于查找当前环境变量中是否存在这个名字 的环境变量 ； vars () 函数不携带参数，可以返回所有的环境变量 。

### 4.4 const fn

函数可以用 **const关键字**修饰，这样的函数可以在**编译阶段**被编译器执行，返回值也被视为**编译期常量**。

```rust
fn main(){
		const LEN: usize = cube(2);
  	// 常量数组，长度需要是常量 
    const ARR: [i32; LEN] = [2; LEN];
    println!("{:?}", ARR);
}

const fn cube(num: usize) -> usize {
    num * num * num
}
```

const 函数是在编译阶段执行的，因此相比普通函数有许多限制，并非所有的表达式和语 句都可以在其中使用 。

目前rust这个功能还没有完全稳定，暂不研究过深。

### 4.5 支持递归函数

Rust允许函数的递归调用。

```rust
// 经典Fibonacci
fn fib(index: u32) -> u64 {
    if index == 1 || index == 2 {
        1
    } else {
        fib(index - 1) + fib(index - 2)
    }
}
```

说到递归，一定会想到“尾递归优化”。可惜当前版本rust暂时不支持尾递归优化，如果递归调用层次太多，依然有可能**撑爆栈空间**。

